### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by AgustinCastellon** [Leonel1320/Ecommers-MercadoLibre#1]
-[ ] 1 - Cumple con todos los elementos en cada sección.
-[ ] 2 - Los elementos están centrados pero los íconos no cuentan con un margen inferior de 10 px.
-[ ] 3 - Cumple. El sitio se adapta a las distintas resoluciones de pantalla-
-[ ] 4 - Cumple. El sitio si cuenta con un formulario de registro de usuarios.
-[ ] 5 - Cumple. El sitio si cuenta con un formulario de login.
-[ ] 6 - Cumple. Los formularios muestran mensajes de error al colocar información erronea. 
-[ ] 7 - Cumple. El search bar si es un formulario.
-[ ] 8 - Cumple. El sitio cuenta con animaciones y transiciones de CSS.
-[ ] 9 - En general me parece un buen trabajo. se siguió y respetó cada micro-desafío de las practicas integradoras. 
-[ ] 10 - Se podría mejorar la sección productos, ya que en resolución de escritorio los artículos no están centrados. También podría agregar un link al logo de mercado libre para que redirija a la página principal (home), ya que cuando se está en las páginas de registro y login no hay una opción para volver al inicio.

**Comment by Leonel1320** [comment]
Terminado de centrar la seccion productos y agregue en el logo la redireccion al home
